all: 	
	gcc -g -o Prerna_Output Lexer2.cpp Parser.cpp -lstdc++
	./Prerna_Output test07.txt out07.txt
	./Prerna_Output test35.txt out35.txt
	./Prerna_Output test34.txt out34.txt
	./Prerna_Output test31.txt out31.txt
	./Prerna_Output test28.txt out28.txt
	./Prerna_Output test27.txt out27.txt
	./Prerna_Output test20.txt out20.txt
	./Prerna_Output test21.txt out21.txt
	./Prerna_Output test25.txt out25.txt
